### ISSUE TITLE
Alpha-3 L2 Explorer dark mode glitch

### ISSUE THREAD

**Issue by MolkerV** [taikoxyz/taiko-mono#14530] opened 2023-08-17 03:43 UTC
### Describe the bug

When dark mode is selected and any transaction or wallet address hyperlink is clicked in the explorer, the screen temporarily switches to light (bright) mode until the new page has loaded completely.

### Steps to reproduce

Load any wallet address into the https://explorer.test.taiko.xyz/ search bar, choose dark mode using the moon selector at the top right, then click on any transaction or contract address link.

**Comment by d1onys1us** [comment] 2023-08-21 21:15
closing as duplicate of #14532

**Closed by d1onys1us** 2023-08-21 21:15 UTC
Labels: category.bug
