### ISSUE TITLE
Add Polyehdra Network to Taiko's Ecosystem

### ISSUE THREAD

**Issue by AntPoly** [taikoxyz/taiko-mono#14175] opened 2023-07-15 09:36 UTC
### Title of your project

Polyhedra Network

### Short (1-2 sentence) description of your project

Polyhedra Network is building the infrastructure for Web3 interoperability with efficient zero-knowledge proof protocols. Polyhedra Network designs and implements zkBridge, providing trustless and efficient cross-chain infrastructures for layer-1 and layer-2 interoperability.

### Link to your project

https://polyhedra.network/ & https://zkbridge.com/

### Please provide evidence here that your project is integrated with Taiko for us to easily check.

https://explorer.test.taiko.xyz/address/0x03dDC4b60D6bBf399A8397d73462060FdFb83476

**Comment by d1onys1us** [comment] 2023-07-15 21:04
closing as duplicate of #14176

**Closed by d1onys1us** 2023-07-15 21:04 UTC
Labels: category.enhancement, status.needs-triage
