### ISSUE TITLE
fix: Taiko wallet shows 50 ETH but metamask shows 0 ETH

### ISSUE THREAD

**Issue by cherbert0123** [taikoxyz/taiko-mono#13608] opened 2023-04-15 16:11 UTC
### Describe the bug

I have done some transfers but they never arrived into the taiko account from sepolia. Then when I go to Taiko network, shows 50 ETH but nothing in my wallet.

### Steps to reproduce

wallet is 0xf9178e809CEFaF2b219787336650A31552e52d5f

### Additional context

report the bug as incorrect balance showing

**Comment by d1onys1us** [comment] 2023-04-25 17:12
adding this to the list of things to check for the alpha-3 testnet, thanks

**Comment by jscriptcoder** [comment] 2023-05-15 07:23
I could not reproduce this issue. Closing, but keeping an eye as I continue to test different edge-cases.

**Closed by jscriptcoder** 2023-05-15 07:23 UTC
Labels: category.bug, meta.alpha-3, area.developer-experience
