### ISSUE TITLE
Horse token can't be bridged from taiko to ethereum

### ISSUE THREAD

**Issue by trezagit** [taikoxyz/taiko-mono#13081] opened 2023-01-31 22:57 UTC
### Describe the feature request

Description of the feature request here.Horse token can't be bridged from taiko to ethereum

### Describe alternatives you've considered

There is no alternative

### Additional context

Additional context here.

**Comment by dantaik** [comment] 2023-02-02 07:48
@shadab-taiko please confirm whether this is true.

**Comment by shadab-taiko** [comment] 2023-02-03 07:10
Hi @trezagit could you give us more details as to what error you are facing when trying to bridge HORSE from L2 to L1?

I was able to successfully bridge HORSE from L2 to L1, pasting my transactions for your reference:
Bridge transaction on L2: https://l2explorer.a1.taiko.xyz/tx/0xa25e8992f493dc0199ec14df20fce16ec83d0f1d9b9b8ecd98b4982df11744a0

Claim transaction on L1:
https://l1explorer.a1.taiko.xyz/tx/0x98632bd000a4da9419a861a41b0a4b44905fa52fddadc15811c8f09c1f4e4d9e/internal-transactions

**Comment by 0xWhiteGod** [comment] 2023-02-05 16:33
Hello. See what could be the problem.

First of all, you need to send tokens from ETH to Taiko, and in this case, transactions with a round amount of 1000 2000 3000 simply do not reach the user. I think this is a bug.

Solution: try to send an amount like 512 HORSE and then everything should reach Taiko and be fine.

Here are my transactions: https://l1explorer.a1.taiko.xyz/tx/0x8b8cc08c33edd6751682a0c6bca4bfea01244aeadc3e32cada9be0521338eef3 ( didnt get horse ) 
https://l1explorer.a1.taiko.xyz/tx/0xfbcfbf9e371be3c233ad65f9b38ecd55efef64729c1dadf6cc0883ea66a1e4ea ( got horse )
See HORSE amount

After pending i claimed horse: https://l2explorer.a1.taiko.xyz/tx/0x557ed071d839c26a1262a0ec0f588937a8f36e4a45c9a92e44fb80d68aa719aa

And sent back to ETH: https://l2explorer.a1.taiko.xyz/tx/0xd3f76c2a18932522946316c076037eb1f5dae3e8f7f8192b147d6dc0acd8c608

Was glad to help you. WhiteGod#8401

**Comment by cyberhorsey** [comment] 2023-02-08 00:56
@0xWhiteGod the first transaction you listed is an `approval` for ERC20 `approve` method. 
To be able to bridge you must first `approve` then `transfer`.
You `approved` for 1000, then `transfer` for 512.

**Comment by 0xWhiteGod** [comment] 2023-02-08 12:23
> @0xWhiteGod the first transaction you listed is an `approval` for ERC20 `approve` method. To be able to bridge you must first `approve` then `transfer`. You `approved` for 1000, then `transfer` for 512.

After that, I tried again to send 1000 and 1500, and still nothing worked.

**Comment by shadab-taiko** [comment] 2023-02-08 13:57
Hey @0xWhiteGod , here's a step by step along with some screenshots to help you bridge ERC20 tokens:
- Enter the amount in the field and `Approve` the bridge contract to be able transfer the ERC20 tokens. Metamask (or whichever wallet you are using) pops up and asks you to submit a transaction.
![Screenshot 2023-02-08 at 6 22 22 PM](https://user-images.githubusercontent.com/108871478/217535665-f11d7af9-5606-4948-a545-c0dc32362824.png)


- The button on the UI now changes to `Bridge`. Clicking on it will again pop up your wallet to send a second transaction.
![Screenshot 2023-02-08 at 6 22 53 PM](https://user-images.githubusercontent.com/108871478/217535703-f5a3a635-765a-4a10-89db-fa8b28614616.png)


- After the above transaction is confirmed you can see the transaction in the transactions tab
![Screenshot 2023-02-08 at 6 24 03 PM](https://user-images.githubusercontent.com/108871478/217535734-9c3cc18a-0ba2-4f46-bf83-1e520a9b64ed.png)

- You will have to wait some time before the tokens can be claimed on the destination chain. Once you see the `Claim` button and click on it, depending on which chain you wallet is currently pointed to:
     - If bridging from L2 to L1 and you are on L2, the wallet will first pop up and ask you to confirm switching the chain to L1 
       and then pop up to ask you submit the `Claim` transaction. If the wallet doesn't ask you to switch the chain you can 
       first change the chain manually in the wallet and then come back to the UI and click on `Claim` again.
     - If bridging from L2 to L1 and you are on L1 the wallet will straightaway pop up to ask you submit the `Claim` 
        transaction.
        
        
Also sharing with you links to my transactions bridging 1000 HORSE from Taiko (L2) to Ethereum (L1):
ERC20 Approval: https://l2explorer.a1.taiko.xyz/tx/0xdc6d88c528b3b7be9ff8aeef4f128e093c44fdef63e41b5d4dcdc159bbe80b2a

Bridging: https://l2explorer.a1.taiko.xyz/tx/0xd5a54ca8530ea639cf585762343bbcf7b33ee5c1a206f1ebfe1eee7b6f555709

Claim on L1: https://l1explorer.a1.taiko.xyz/tx/0x2839e90da5745630675c63a95d66ea14d44743121a5e2fef34203b59fdd2dc76

**Comment by cyberhorsey** [comment] 2023-03-06 19:15
Closing due to duplciate issue + seems to be issue on user's end, only approved.

**Closed by cyberhorsey** 2023-03-06 19:15 UTC
Labels: bridge
